### ISSUE TITLE
Slurm accounting not accumulating data

### ISSUE THREAD

**Issue by christopheredsall** [ACRC/slurm-ansible-playbook#10]
A cluster user has reported that ``sacct``shows no results 

```
[opc@mgmt ~]$ date
Thu 28 Feb 10:34:20 GMT 2019
[opc@mgmt ~]$ sacct --starttime=2019-01-01
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
[opc@mgmt ~]$ 
```

**Comment by milliams** [comment]
It looks like this can be fixed with a restart of `slurmctld` since it has some trouble reaching `slurmdbd`. I'm having a look now to see if the ansible can be tweaked to restart ctld after dbd.
