### ISSUE TITLE
Port to Google cloud

### ISSUE THREAD

**Issue by milliams** [ACRC/slurm-ansible-playbook#16]

**Comment by christopheredsall** [comment]
## Conditional Execution in Ansible

 

Is there a variable and value that we can use as a [condition](https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html) which code to execute when running the playbooks?

 

Is there a module that abstracts out the different cloud vendors?

 

### Built-in facts

 

(making use of [Ansible and jq](https://medium.com/@george.shuklin/ansible-and-jq-9d8e50ec3379) )

 

#### Oracle

```ShellSession
[ce16990@mgmt ~]$ ansible -m setup localhost |sed '1c {'| jq '.ansible_facts.ansible_system_vendor' 
"QEMU"
```

#### Google

```ShellSession
[ce16990@ce16990-ansible-test ~]$  ansible -m setup localhost |sed '1c {'| jq '.ansible_facts.ansible_system_vendor' 
"Google"
```

#### Azure

```ShellSession
[ce16990@ce16990-bristol-test ~]$ ansible -m setup localhost |sed '1c {'| jq '.ansible_facts.ansible_system_vendor'
"Microsoft Corporation"
```
 
#### IBM

```ShellSession
[root@virtualserver01 ~]# ansible -m setup localhost |sed '1c {'| jq '.ansible_facts.ansible_system_vendor'
"Xen"
``` 

#### AWS

 ```ShellSession
[ec2-user@ip-172-31-36-201 ~]$ ansible -m setup localhost |sed '1c {'| jq '.ansible_facts.ansible_system_vendor'
"Xen"
```

Looking at the rest of the facts there doesn't appear to be a consistent single parameter that we can use. We could come up with a heuristic to detect the vendor but that feels a bit fragile.

### Custom facts

In a whiteboard session with the team from [Appsbroker](https://www.appsbroker.com/) (@geoffnewell, @davidyo, @ab-philburke) David pointed out  that we can define our own [local facts](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#local-facts-facts-d)

For passing the information in from the [terraform](https://github.com/ACRC/oci-cluster-terraform) we settled on a name `csp` for Cloud Service Provider and values 

Cloud Service Provider | `csp` value
------------ | -------------
Oracle | `oci`
Google | `google-cloud`

e.g. in the file `/etc/ansible/facts.d/citc.fact`  adding

```json
{"csp":"google-cloud"}
```

Results in 

```ShellSession
[ce16990@ce16990-ansible-test ~]$ ansible -m setup localhost  |sed '1c {'| jq '.ansible_facts.ansible_local.citc.csp'
"google-cloud"
```
