### ISSUE TITLE
Node started with script is in wrong state

### ISSUE THREAD

**Issue by 63990** [ACRC/slurm-ansible-playbook#3]
In a newly build cluster, when I run 
`sudo -u slurm /usr/local/bin/startnode compute001`

I get the error message: 
`slurm_update error: Invalid node state specified`

and the node state according to slurm is:
```
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
compute*     up   infinite      1   down compute001
```

In `/home/slurm/elastic.log` :
```
Wed Dec 19 15:57:41 GMT 2018: Stopping compute001
Wed Dec 19 15:57:45 GMT 2018:   Stopped compute001
Wed 19 Dec 16:01:05 GMT 2018: Starting compute001
Wed 19 Dec 16:01:08 GMT 2018:   Started compute001
```

and in `/var/log/slurm/slurmmctld.log` : 
```
[2018-12-19T15:57:51.140] Power save mode: 1 nodes
[2018-12-19T16:01:08.682] Invalid node state transition requested for node compute001 from=IDLE~ to=RESUME
[2018-12-19T16:01:08.683] got (nil)
[2018-12-19T16:01:08.683] _slurm_rpc_update_node for compute001: Invalid node state specified
[2018-12-19T16:02:13.534] Node compute001 now responding
[2018-12-19T16:02:13.534] validate_node_specs: Node compute001 unexpectedly rebooted boot_time=1545235293 last response=1545234960
```

**Comment by christopheredsall** [comment]
Thanks for reporting that. I can duplicate the issue. As a workaround you can set a node into the idle state ready to receive jobs with

```
scontrol update NodeName=compute001 State=Resume
```

You can use normal slurm noderange expressions e.g. `compute[001-200]` in that command.

**Comment by milliams** [comment]
It is not recommended to start nodes manually using `startnode` script as this causes the node to start "behind Slurm's back". When this script is run by Slurm's internals it does more than simply call it, it manages other Slurm internal state. If you do call it directly, you will need to run the line that Chris says.

The recommended way is to simply let Slurm start the node itself by submitting a job.
