### ISSUE TITLE
Unable to view montior network performance

### ISSUE THREAD

**Issue by 63990** [ACRC/slurm-ansible-playbook#4]
I am using Grafana dashboard 928 to monitor performance on an OCI cluster but cannot see any data points for network activity.

The telegraf.conf file on the cluster has the following commented out (line 2787 onwards):
* input.net
* input.netstats
* input.interrupts

So to monitor them telegraf has to run again with the above included.

**Comment by christopheredsall** [comment]
Using the patch in the PR I was able to see network graphs in grafana

![ens3-packets](https://user-images.githubusercontent.com/1021204/52643684-722d6480-2ed5-11e9-9703-f43060cfd0f6.png)
![ens3-bytes](https://user-images.githubusercontent.com/1021204/52643687-748fbe80-2ed5-11e9-955b-4635d4858d85.png)
