### ISSUE TITLE
ansible fails on TASK [users : install ldap3 in central Python 3] 

### ISSUE THREAD

**Issue by christopheredsall** [ACRC/slurm-ansible-playbook#85]
On a fresh install the ansible run on the management server fails with

``` 
TASK [users : install ldap3 in central Python 3] *******************************
Sunday 04 October 2020  18:41:24 +0000 (0:00:00.522)       0:02:34.783 ******** 
fatal: [mgmt.excited-krill.citc.local]: FAILED! => changed=false 
  failures: []
  msg: |-
    Depsolve Error occured:
     Problem: conflicting requests
      - nothing provides python3.6dist(pyasn1) >= 0.4.6 needed by python3-ldap3-2.8.1-1.el8.noarch
  rc: 1
  results: []
```

**Comment by christopheredsall** [comment]
Can't install on the commandline either

```ShellSession
[citc@mgmt ~]$ sudo yum -y install python3-ldap3
Last metadata expiration check: 0:02:38 ago on Sun 04 Oct 2020 18:47:06 UTC.
Error: 
 Problem: conflicting requests
  - nothing provides python3.6dist(pyasn1) >= 0.4.6 needed by python3-ldap3-2.8.1-1.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by christopheredsall** [comment]
It seems the version in the configured repos is too old

```ShellSession
[citc@mgmt ~]$ yum info python3-pyasn1 | grep -E 'Name|Version'
Name         : python3-pyasn1
Version      : 0.3.7
```

**Comment by christopheredsall** [comment]
Upstream package changed the required version of `python3-pyasn1` in https://github.com/cannatag/ldap3/commit/391aa243cadfc3f68fa079f95e0375e05839c90f#diff-b4ef698db8ca845e5845c4618278f29a

EPEL who package `python3-ldap3` don't appear to tag a version of [python3-pyasn1](https://koji.fedoraproject.org/koji/packageinfo?packageID=24700)  for epel8

**Comment by christopheredsall** [comment]
## Workaround

Grab the source RPM from EPEL 7 and rebuild it

```ShellSession
[citc@mgmt ~]$ sudo yum -y install rpm-build python3-devel python3-setuptools 
[citc@mgmt ~]$ curl -O https://kojipkgs.fedoraproject.org//packages/python3-pyasn1/0.4.7/1.el7/src/python3-pyasn1-0.4.7-1.el7.src.rpm
[citc@mgmt ~]$ rpmbuild --rebuild python3-pyasn1-0.4.7-1.el7.src.rpm
[citc@mgmt ~]$ sudo yum localinstall /home/citc/rpmbuild/RPMS/noarch/python3-pyasn1-0.4.7-1.el8.noarch.rpm
```

Rerun ansible

```ShellSession
[citc@mgmt ~]$ sudo -i
[root@mgmt ~]# /usr/bin/ansible-pull \
    --url=https://github.com/clusterinthecloud/ansible.git \
    --checkout=6 \
    --inventory=/root/hosts management.yml
```

**Comment by milliams** [comment]
Is this on Oracle, AWS or Google? Oracle is stuck on CentOS 7 but the rest are on 8. There's some mentions of el7 and el8 in your commands so it's not clear.

**Comment by christopheredsall** [comment]
> Is this on Oracle, AWS or Google?

In this instance, AWS.

**Comment by milliams** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1885139

**Comment by christopheredsall** [comment]
[BZ#1885139](https://bugzilla.redhat.com/show_bug.cgi?id=1885139) has been updated and now says:

> FEDORA-EPEL-2020-1f361092e3 has been pushed to the Fedora EPEL 8 stable repository.

On a fresh CitC install 

- [x] the ansible playbook runs to completion. 
- [x] an LDAP user can run a slurm job
